name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout
      
      - name: Build and run unit tests
        run: |
          gcc -o quadratic_equation quadratic_equation.c -lm
          ./quadratic_equation
