name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y build-essential libcunit1 libcunit1-dev

    - name: Build
      run: gcc -o quadratic_equation test_quadratic_equation.c -lm

    - name: Run unit tests
      run: ./quadratic_equation
