name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Build and run tests
      run: |
        cmake -S . -B build
        cmake --build build --target all
        cd build
        ./unit_tests
